### PR TITLE
`github_repo_open_issues` and `github_repo_pull_request_count` separately

### PR DESCRIPTION
**Pull request by iamrare**
we needed `github_repo_open_issues` and `github_repo_pull_request_count` separately, so I added it
(GitHub REST API returns all open issues + pull requests count, not issues only, so we have to use the pull requests API to get the PR count and then subtract it to get issues)

please consider merging it upstream in case other people need it
if it's accepted, we can use infinityworks' version rather than maintaining our own

thanks

### CODE REVIEW

**Comment by iamtgray** [comment]
I will have a look at this at some point in the next 12 hours and confirm before merging

**Comment by iamrare** [comment]
looks like it was a requested feature already:
https://github.com/infinityworks/github-exporter/issues/12

**Comment by Rucknar** [comment]
LGTM - @iamtgray ?

**Comment by iamrare** [comment]
Thank you!

**Pull request merged**
