### PR TITLE
support for monitoring users

### PR DESCRIPTION
**Pull request by caarlos0**
so I could for example watch all my own repos :)

### CODE REVIEW

**Comment by Rucknar** [comment]
Give it a try specifying your username under the 'org' flag. Not at a computer now but I think it should work. If not, easy for me to add in.

**Comment by Rucknar** [comment]
Apologies, on my mobile and thought this was an issue.. not a PR. I'll take a look later today, appreciate the contribution :)

**Comment by caarlos0** [comment]
@Rucknar not a problem, it doesn't work passing a user down in the `ORGS` env :)

**Comment by Rucknar** [comment]
Thanks @caarlos0 !

**Pull request merged**
