### PR TITLE
Use docker multistage builds

### PR DESCRIPTION
**Pull request by jlevesy**
Hi folks,

First of all thanks for your amazing job ! 
I just noticed your image is around 100mb for a single go binary.
Using a multistage build I managed to reduce it to 11.6mb, so I thought I should share it :)

(We could gain a few mb more by using a scratch image and disabling CGO support at build time, but it means no user management)

WDYT ?
Cheers !

### CODE REVIEW

**Comment by Rucknar** [comment]
Thanks for the PR @jlevesy !

Whilst i'm keen to merge... As far as I know though, DockerHub doesn't yet support multi-stage builds. This could potentially break the auto-build. 

I'll double check today, could always move the build to docker-cloud which does support it...

**Comment by flock3** [comment]
It doesn't seem to support them yet (https://github.com/docker/hub-feedback/issues/1039) however could we not move the build over to docker-cloud or will that break old container pulls?

**Comment by jlevesy** [comment]
Sorry about that.
I was absolutely unaware that docker-hub doesn't support multistage builds.

**Comment by Rucknar** [comment]
No worries!
It's definitely the nicer solution. It should be arriving once 17.06 is released, i'm led to believe that will be in the next week or two.

**Comment by Rucknar** [comment]
Moved to Docker Cloud builds, supports multi-stage.

**Pull request merged**
